trigger:
  name: Main deployment
  identifier: Main_deployment
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  tags: {}
  orgIdentifier: default
  stagesToExecute: []
  projectIdentifier: default_project
  pipelineIdentifier: guestbook_canary_pipeline
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: harnessgitconnector
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Regex
              value: master
          headerConditions: []
          actions: []
  inputYaml: |
    pipeline: {}
